[project]
name = "cardio-rl"
version = "0.1.2"
description = "Cardio RL. In development..."
authors = [{name = "Manus McAuliffe", email = "mmcaulif@tcd.ie"}]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10, <3.12"
classifiers = [
        "Development Status :: 3 - Alpha",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
]
dependencies = [
        "numpy>=1.21.0",
        "gymnasium>=0.28.0",
        "tqdm>=4.66.5",
        "jax>=0.4.25,<0.4.30",
        "jaxlib>=0.4.25,<0.4.30",
]

[project.optional-dependencies]
logging = [
        "wandb>=0.18.5",
        "tensorboard>=2.18.0",
        "torch>=1.12.1",
]
agents = [
        "distrax==0.1.5",
        "rlax==0.1.6",
        "flax==0.8.3",
        "optax==0.2.2",
]

[project.urls]
Repository = "https://github.com/mmcaulif/Cardio"

[dependency-groups]
dev = [
        "ruff>=0.7.0",
        "mypy>=1.12.0",
        "pre-commit>=4.0.1",
        "isort>=5.13.2",
        "pytest>=8.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
extend-select = [
        "D",    # pydocstyle
        "I",    # isort
]
exclude = ["tests/*", "examples/*", "cardio_rl/buffers/prioritised_buffer.py"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.docformatter]
post-description-newline = true

[tool.mypy]
ignore_missing_imports = true
