name: Cardio Precommits
run-name: ${{ github.actor }}
on: [push]
jobs:
  pre-commits:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: pre-commit-lite
          uses: pre-commit-ci/lite-action@v1.1.0
          if: always()

        # - name: pre-commit
        #   uses: pre-commit/action@v3.0.1
        # TODO: The above causes an error in CI, need to fix at some point
