name: Cardio Precommits
run-name: ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
            architecture: 'x64'

        # Precommit
        - name: pre-commit
          uses: pre-commit-ci/lite-action@v1.1.0
