name: Cardio Tests
run-name: ${{ github.actor }}
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pipx install poetry

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # - name: Update Poetry configuration
      #   run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install

      # Testing
      - name: Test with pytest
        run: |
          poetry run pip install pytest-cov
          poetry run pytest .
